export const API_END_POINTS = {
  baseURL: 'https://jerotoma.com',
  dashboard: '/dashboard',
  rootURL: '/api/secured',
  users: '/api/secured/users',
  refreshToken: '/api/auth/refresh-token',
  login: '/api/auth/login',
  register: '/api/auth/register',
  resetPassword: '/api/auth/reset-password',
  logout: '/api/auth/sign-out',
  positions: '/api/secured/positions',
  academicDisciplines: '/api/secured/academic-disciplines',
  rooms: '/api/secured/rooms',
  courses: '/api/secured/courses',
  programs: '/api/secured/programs',
  departments: '/api/secured/departments',
  meetingTimes: '/api/secured/meeting-times',
  workDays: '/api/secured/work-days',
  academicYears: '/api/secured/academic-years',
  classes: '/api/secured/classes',
  studentClasses: '/api/secured/student-classes',
  uploads: '/api/secured/uploads',
  themes: '/api/secured/themes',
  pubThemes: '/api/public/themes',
  systemConfigs: '/api/secured/system-configs',
  pubSystemConfigs: '/api/public/system-configs',
  userPreferences: '/api/secured/user-preferences',
  pubUserPreferences: '/api/public/user-preferences',
  restDashboard: '/api/secured/dashboard',
  attendances: '/api/secured/attendances',
  academicLevels: '/api/secured/academic-levels',
};


export const FRONT_END_POINTS = {
  baseURL: 'https://jerotoma.com',
  dashboard: '/dashboard',
  login: '/account/login',
  resources: '/dashboard/resources',
  users: '/dashboard/users',
  staffs: '/dashboard/users/staffs',
  teachers: '/dashboard/users/teachers',
  parents: '/dashboard/users/parents',
  students: '/dashboard/users/students',
};
