export const END_POINTS = {
  dashboard: '/dashboard',
  rootURL: '/api/secured',
  users: '/api/secured/users',
  refreshToken: '/api/auth/refresh-token',
  login: '/api/auth/login',
  register: '/api/auth/register',
  resetPassword: '/api/auth/reset-password',
  logout: '/api/auth/sign-out',
  positions: '/api/secured/positions',
  academicDisciplines: '/api/secured/academic-disciplines',
  rooms: '/api/secured/rooms',
  courses: '/api/secured/courses',
  departments: '/api/secured/departments',
  meetingTimes: '/api/secured/meeting-times',
  workDays: '/api/secured/work-days',
  academicYears: '/api/secured/academic-years',
  classes: '/api/secured/classes',
  studentClasses: '/api/secured/student-classes',
  uploads: '/api/secured/uploads',
  themes: '/api/secured/themes',
  pubThemes: '/api/public/themes',
  systemConfigs: '/api/secured/system-configs',
  pubSystemConfigs: '/api/public/system-configs',
  userPreferences: '/api/secured/user-preferences',
  pubUserPreferences: '/api/public/user-preferences',
  restDashboard: '/api/secured/dashboard',

};
