export const END_POINTS = {
  dashboard: '/dashboard',
  rootURL: '/api/secured',
  users: '/api/secured/users',
  refreshToken: '/api/auth/refresh-token',
  login: '/api/auth/login',
  register: '/api/auth/register',
  resetPassword: '/api/auth/reset-password',
  logout: '/api/auth/sign-out',
  positions: '/api/secured/positions',
  academicDisciplines: '/api/secured/academic-disciplines',
  classRooms: '/api/secured/class-rooms',
  courses: '/api/secured/courses',
  academicYears: '/api/secured/academic-years',
  classes: '/api/secured/classes',
  studentClasses: '/api/secured/student-classes',
  uploads: '/api/secured/uploads',
  systemConfigs: '/api/secured/system-configs',
  pubSystemConfigs: '/api/public/system-configs',
  userPreferences: '/api/secured/user-preferences',
  pubUserPreferences: '/api/public/user-preferences',

};
