export enum USER_ROLE {
  SUPER_ADMIN = 'ROLE_ADMIN',
  ADMIN = 'ROLE_ADMIN',
  TEACHER = 'ROLE_TEACHER',
  PRINCIPAL = 'ROLE_PRINCIPAL',
  PARENT = 'ROLE_PARENT',
  STUDENT = 'ROLE_STUDENT',
  STAFF = 'ROLE_STAFF',
  LIBRARIAN = 'ROLE_LIBRARIAN',
  USER = 'ROLE_USER',
  ANANYMOUS = 'ROLE_ANANYMOUS',
}

export const ALL_ROLES = Object.values(USER_ROLE);
export const STAFF_ONLY_ROLES = [USER_ROLE.STAFF];
export const STAFF_AND_TEACHER_ROLES = [USER_ROLE.TEACHER, USER_ROLE.STAFF];
export const TEACHER_AND_EXECUTIVES_ROLES = [USER_ROLE.TEACHER, USER_ROLE.PRINCIPAL];
export const ADMINS_AND_EXECUTIVES_ROLES = [USER_ROLE.ADMIN, USER_ROLE.SUPER_ADMIN, USER_ROLE.PRINCIPAL];
export const ADMINS_TEACHER_AND_EXECUTIVES_ROLES = [USER_ROLE.ADMIN, USER_ROLE.SUPER_ADMIN, USER_ROLE.TEACHER, USER_ROLE.PRINCIPAL];
export const ADMINS_ONLY_ROLES = [USER_ROLE.ADMIN, USER_ROLE.SUPER_ADMIN];
export const STUDENT_AND_TEACHER_ROLES = [USER_ROLE.STUDENT, USER_ROLE.TEACHER];
export const STUDENT_PARENT_AND_TEACHER_ROLES = [USER_ROLE.STUDENT, USER_ROLE.PARENT, USER_ROLE.TEACHER];
export const ADMINS_STAFF_TEACHER_AND_EXECUTIVES_ROLES = [USER_ROLE.ADMIN, USER_ROLE.SUPER_ADMIN, USER_ROLE.TEACHER, USER_ROLE.PRINCIPAL, USER_ROLE.STAFF];
export const PARENT_AND_TEACHER_ROLES = [USER_ROLE.PARENT];
export const ADMINS_PARENT_TEACHER_AND_EXECUTIVES_ROLES = [USER_ROLE.ADMIN, USER_ROLE.SUPER_ADMIN, USER_ROLE.TEACHER, USER_ROLE.PRINCIPAL, USER_ROLE.PARENT];
export const ADMINS_STUDENT_PARENT_TEACHER_AND_EXECUTIVES_ROLES = [USER_ROLE.ADMIN, USER_ROLE.SUPER_ADMIN, USER_ROLE.TEACHER, USER_ROLE.PRINCIPAL, USER_ROLE.PARENT];
export const ADMINS_PARENT_AND_EXECUTIVES_ROLES = [USER_ROLE.ADMIN, USER_ROLE.SUPER_ADMIN, USER_ROLE.PRINCIPAL, USER_ROLE.PARENT];
export const ADMINS_STAFF_AND_EXECUTIVES_ROLES = [USER_ROLE.ADMIN, USER_ROLE.SUPER_ADMIN, USER_ROLE.PRINCIPAL, USER_ROLE.STAFF];

