export enum USER_ROLE {
  SUPER_ADMIN = 'ROLE_ADMIN',
  ADMIN = 'ROLE_ADMIN',
  TEACHER = 'ROLE_TEACHER',
  PRINCIPAL = 'ROLE_PRINCIPAL',
  PARENT = 'ROLE_PARENT',
  STUDENT = 'ROLE_STUDENT',
  STAFF = 'ROLE_STAFF',
  LIBRARIAN = 'ROLE_LIBRARIAN',
  USER = 'ROLE_USER',
  ANANYMOUS = 'ROLE_ANANYMOUS',
}

export const ALL_ROLES = Object.values(USER_ROLE);

